# Generated by Django 5.1.6 on 2025-04-05 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('end_time', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('EVENT_ORGANIZER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.event_organizer')),
            ],
        ),
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('EVENT_ORGANIZER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.event_organizer')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.login')),
            ],
        ),
        migrations.AddField(
            model_name='event_organizer',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.login'),
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('EVENT_ORGANIZER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.event_organizer')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('stage_latitude', models.CharField(max_length=100)),
                ('stage_longitude', models.CharField(max_length=100)),
                ('stage_no', models.CharField(max_length=100)),
                ('EVENT_ORGANIZER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('PROGRAM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.program')),
            ],
        ),
        migrations.CreateModel(
            name='allocate_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JUDGE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.judge')),
                ('PROGRAM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.program')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=100)),
                ('end_tim', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('EVENT_ORGANIZER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.event_organizer')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('COLLEGE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.college')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='assign_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('COLLEGE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.college')),
                ('STAFF', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.login')),
                ('STAFF', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('JUDGE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.judge')),
                ('PROGRAM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.program')),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='program_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('PROGRAM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.program')),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.student')),
            ],
        ),
    ]
