# Generated by Django 3.2.25 on 2025-03-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest_hub_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='STAFF',
        ),
        migrations.AddField(
            model_name='notification',
            name='PROGRAM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest_hub_app.program'),
        ),
        migrations.DeleteModel(
            name='assign_judge_work',
        ),
    ]
