# Generated by Django 3.2.25 on 2025-03-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_hub_app', '0003_auto_20250309_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='latitude',
            new_name='stage_latitude',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='longitude',
            new_name='stage_longitude',
        ),
    ]
