# Generated by Django 5.1.6 on 2025-03-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_hub_app', '0004_auto_20250309_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='rounds',
        ),
    ]
