# Generated by Django 5.1.6 on 2025-03-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_hub_app', '0005_remove_program_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='JUDGE',
        ),
    ]
