# Generated by Django 5.1.6 on 2025-03-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_hub_app', '0006_remove_event_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_organizer',
            name='venue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
