# Generated by Django 5.1.6 on 2025-02-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_table',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventorganizer_table',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
